CREATE TABLE IF NOT EXISTS `ABUSE` (
  

`ID` int(11) NOT NULL AUTO_INCREMENT,
  

`USER_ID` int(11) DEFAULT NULL,
`OBJECT_ID` int(11) DEFAULT NULL,   

`TIME` int(11) DEFAULT NULL,
   

`MESSAGE` varchar(1000) DEFAULT NULL,

`REASON` int(11) DEFAULT '0',
`OBJECT_TYPE` varchar(30) DEFAULT NULL,

`READ` int(11) DEFAULT '0',

PRIMARY KEY (`ID`)

) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;