CREATE TABLE `ATTACHMENTS` (

`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`USER_ID` int(11) DEFAULT NULL,
  
`TYPE` varchar(100) DEFAULT NULL,
  
`OBJECT_ID` int(11) DEFAULT NULL,
  
`ID_POST` int(11) DEFAULT NULL,
  
`TYPE_POST` varchar(100) DEFAULT NULL,
  
`COMMENTS` int(11) DEFAULT '0',
  
`BLOGS` int(11) DEFAULT '0',
  
`NEWS` int(11) DEFAULT '0',
  
`ACT` int(11) DEFAULT '0',
  
`TIME` int(11) DEFAULT NULL,
  
`FORUM` int(11) DEFAULT '0',
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;