CREATE TABLE IF NOT EXISTS `BANNERS` (
  

`ID` int(11) NOT NULL AUTO_INCREMENT,
  

`ACT` int(11) DEFAULT '1',
      
`CODE` varchar(1500) NOT NULL,
 
`TYPE` int(11) DEFAULT '1',
 
PRIMARY KEY (`ID`)

) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;