CREATE TABLE `BLOGS` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`USER_ID` int(11) DEFAULT '0',
  
`TIME` int(11) DEFAULT '0',
  
`NAME` varchar(200) DEFAULT NULL,
  
`MESSAGE` varchar(10000) DEFAULT NULL,
  
`PRIVATE` int(11) DEFAULT '0',
  
`ID_CATEGORY` int(11) DEFAULT '0',
  
`PRIVATE_COMMENTS` int(11) DEFAULT '0',
  
`PASSWORD` varchar(300) DEFAULT NULL,
  
`PASSWORD_SHOW` varchar(100) DEFAULT NULL,
  
`RATING` double(10,2) DEFAULT '0.00',
  
`COMMUNITY` int(11) DEFAULT '0',
  
`SHARE` int(11) DEFAULT '0',

PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;