
CREATE TABLE IF NOT EXISTS `COMMUNITIES_CATEGORIES` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`NAME` varchar(300) DEFAULT NULL,
PRIMARY KEY (`ID`))
ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
