CREATE TABLE IF NOT EXISTS `COMMUNITIES_FORUM_THEM` (
  

`ID` int(11) NOT NULL AUTO_INCREMENT,
       
`NAME` varchar(200) NOT NULL,
 

`MESSAGE` varchar(10000) NOT NULL,

`SECTION_ID` int(11) NOT NULL,

`USER_ID` int(11) NOT NULL,

`TIME` int(11) NOT NULL,

`BAN` int(11) DEFAULT '0',
`BAN_TYPE` int(11) DEFAULT '0',
 
 
`BAN_COMMENTS` varchar(500) DEFAULT NULL,

`ACTIVE` int(11) DEFAULT '1',
 
`ACTIVE_USER_ID` int(11) DEFAULT NULL,
 
`ACTIVE_TIME` int(11) DEFAULT NULL,

`EDIT_TIME` int(11) DEFAULT NULL,
`EDIT_USER_ID` int(11) DEFAULT NULL,
`RATING` double(10,2) DEFAULT '0',
`COMMUNITY_ID` int(11) NOT NULL,

PRIMARY KEY (`ID`)

) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;