
CREATE TABLE IF NOT EXISTS `COMMUNITIES_JURNAL` (
  

`ID` int(11) NOT NULL AUTO_INCREMENT,

`COMMUNITY_ID` int(11) DEFAULT NULL,

`MESSAGE` varchar(500) DEFAULT NULL,
`TIME` int(11) DEFAULT NULL,


PRIMARY KEY (`ID`)
)
ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;