CREATE TABLE `COMMENTS` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`USER_ID` int(11) DEFAULT NULL,
  
`OBJECT_TYPE` varchar(100) DEFAULT NULL,
  
`OBJECT_ID` int(11) DEFAULT NULL,
  
`SUB_OBJECT_ID` int(11) DEFAULT NULL,
  
`TIME` int(11) DEFAULT NULL,
  
`MESSAGE` varchar(5000) DEFAULT NULL,
  
`REPLY` int(11) DEFAULT '0',
  
`REPLY_USER_ID` int(11) DEFAULT '0',
  
`EDIT_TIME` int(11) DEFAULT NULL,
  
`EDIT_USER_ID` int(11) DEFAULT NULL,
  
`COUNT` int(11) DEFAULT '0',
  
`REPLY_USER` int(11) DEFAULT '0',
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;