CREATE TABLE IF NOT EXISTS `COMMUNITIES_PAR` (
  

`ID` int(11) NOT NULL AUTO_INCREMENT,
  

`COMMUNITY_ID` int(11) NOT NULL,
    

`USER_ID` int(11) NOT NULL,

`ADMINISTRATION` int(11) DEFAULT '0',

`ACT` int(11) DEFAULT '1',

PRIMARY KEY (`ID`)

) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;