CREATE TABLE IF NOT EXISTS `COMMUNITIES_BAN` (
  

`ID` int(11) NOT NULL AUTO_INCREMENT,
  

`COMMUNITY_ID` int(11) NOT NULL,

`ADM_ID` int(11) NOT NULL,
    

`TIME` int(11) NOT NULL,
   

`MESSAGE` varchar(1000) NOT NULL,
  

`BAN` int(11) DEFAULT '0',

`BAN_TIME` int(11) DEFAULT '0',
`REASON` int(11) DEFAULT '0',
PRIMARY KEY (`ID`)

) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;