CREATE TABLE `COMMUNITIES` ( 
`ID` int(11) NOT NULL AUTO_INCREMENT,  
`USER_ID` int(11) DEFAULT NULL,  
`TIME` int(11) DEFAULT NULL,  
`NAME` varchar(200) DEFAULT NULL,  
`MESSAGE` varchar(5000) DEFAULT NULL,  
`PRIVATE` int(1) DEFAULT '0',  
`ID_CATEGORY` int(11) DEFAULT '0',  
`RATING` double(10,2) DEFAULT '0.00',  
`AVATAR` int(11) DEFAULT '0',  
`SCREENSAVER` int(11) DEFAULT '0',  
`MOTTO` varchar(500) DEFAULT NULL,  
`RULES` varchar(1000) DEFAULT NULL,  
`INTERESTS` varchar(500) DEFAULT NULL,  
`URL` varchar(120) DEFAULT NULL,
`BAN` int(1) DEFAULT '0',
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;
