CREATE TABLE `DOWNLOADS` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`TIME` int(11) NOT NULL,
  
`USER_ID` int(11) NOT NULL,
  
`OBJECT_ID` int(11) NOT NULL,
  
`OBJECT_TYPE` varchar(100) NOT NULL,
  
`ID_DIR` int(11) NOT NULL,
  
`ID_DIR_O` int(11) DEFAULT NULL,
  
`RATING` int(11) DEFAULT NULL,
  
`NAME` varchar(200) DEFAULT NULL,
  
`MESSAGE` varchar(1000) DEFAULT NULL,
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;