CREATE TABLE `EYE` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`TIME` int(11) NOT NULL,
  
`USER_ID` int(11) NOT NULL,
  
`OBJECT_ID` int(11) NOT NULL,
  
`TYPE` varchar(100) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;