CREATE TABLE `FORUM_SUB_SECTION` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`NAME` varchar(200) NOT NULL,
  
`MESSAGE` varchar(300) NOT NULL,
  
`SECTION_ID` int(11) NOT NULL,
  
`RATING` int(11) DEFAULT '0',
  
`PRIVATE` int(11) DEFAULT '0',
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;