CREATE TABLE IF NOT EXISTS `FORUM_SECTION` (
  

`ID` int(11) NOT NULL AUTO_INCREMENT,
       
`NAME` varchar(200) NOT NULL,
 

`MESSAGE` varchar(300) NOT NULL,

PRIMARY KEY (`ID`)

) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;