
CREATE TABLE IF NOT EXISTS `FRIENDS` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`USER_ID` int(11) DEFAULT NULL,
`MY_ID` int(11) DEFAULT NULL,
`ACT` int(11) DEFAULT '1',
`TIME` int(11) DEFAULT NULL,
PRIMARY KEY (`ID`))
ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
