
CREATE TABLE IF NOT EXISTS `GAMES` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`NAME` varchar(150) DEFAULT NULL,
`LINK` varchar(250) DEFAULT NULL,
`MESSAGE` varchar(1000) DEFAULT NULL,
`IMG` varchar(100) DEFAULT 'img.png',
`TIME` int(11) DEFAULT NULL,
`RATING` int(11) DEFAULT '0',
PRIMARY KEY (`ID`))
ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
