
CREATE TABLE IF NOT EXISTS `GIFTS_USER` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`MESSAGE` varchar(300) DEFAULT NULL,
`USER_ID` int(11) DEFAULT NULL,
`MY_ID` int(11) DEFAULT NULL,
`GIFT_ID` int(11) DEFAULT NULL,
`PRIVATE` int(11) DEFAULT '0',
`TIME` int(11) DEFAULT NULL,
PRIMARY KEY (`ID`))
ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;