
CREATE TABLE IF NOT EXISTS `GUESTS` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`IP` varchar(100) DEFAULT NULL,
`BROWSER` varchar(200) DEFAULT NULL,
`DATE_CREATE` int(11) DEFAULT NULL,
`DATE_VISIT` int(11) DEFAULT NULL,
`DATE_VISIT_TIME` int(11) DEFAULT NULL,
`TRANSITIONS` int(11) DEFAULT NULL,
PRIMARY KEY (`ID`))
ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
