CREATE TABLE `INFO` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`TIME` int(11) NOT NULL,
  
`MESSAGE` varchar(5000) NOT NULL,
  
`NAME` varchar(300) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;