
CREATE TABLE IF NOT EXISTS `LANGUAGES` (
  
`NAME` varchar(250) DEFAULT NULL,
`FACT_NAME` varchar(50) DEFAULT NULL,
`ACT` int(11) DEFAULT '1'
)
ENGINE=MyISAM DEFAULT CHARSET=utf8;




INSERT INTO `LANGUAGES` (`NAME`, `FACT_NAME`, `ACT`) VALUES
('English', 'EN', 1);