CREATE TABLE `LICENSE` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`DOMAIN` varchar(300) DEFAULT NULL,
  
`LICENSE` varchar(500) DEFAULT NULL,
  
`TIME` varchar(300) DEFAULT NULL,
  
`KEY` varchar(300) DEFAULT NULL,
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;