CREATE TABLE `LIKES` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`USER_ID` int(11) DEFAULT NULL,
  
`OBJECT_TYPE` varchar(100) DEFAULT NULL,
  
`OBJECT_ID` int(11) DEFAULT NULL,
  
`TIME` int(11) DEFAULT NULL,
  
`TYPE` varchar(50) DEFAULT 'like',
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;