
CREATE TABLE IF NOT EXISTS `MAIL_SETTINGS` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`USER_ID` int(11) DEFAULT '0',
`PRIVATE` int(11) DEFAULT '0',
PRIMARY KEY (`ID`))
ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
