CREATE TABLE `MAIL` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`USER_ID` int(11) NOT NULL,
  
`MY_ID` int(11) NOT NULL,
  
`TIME` int(11) NOT NULL,
  
`TYPE` varchar(200) DEFAULT 'active',
  
`LOGIN` varchar(100) DEFAULT NULL,
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;