CREATE TABLE `MAIL_MESSAGE` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`USER_ID` int(11) NOT NULL,
  
`MY_ID` int(11) NOT NULL,
  
`TIME` int(11) NOT NULL,
  
`MESSAGE` varchar(5000) NOT NULL,
  
`READ` int(11) DEFAULT '0',
  
`USER` int(11) NOT NULL,
  
`UPDATE` int(11) DEFAULT '0',
  
`REPLY` int(11) DEFAULT NULL,
  
`EDIT_TIME` int(11) DEFAULT '0',
  
`TID` int(11) DEFAULT NULL,
  
`SID` varchar(50) DEFAULT NULL,
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;