CREATE TABLE IF NOT EXISTS `NEWS` (
  

`ID` int(11) NOT NULL AUTO_INCREMENT,
  

`USER_ID` int(11) NOT NULL,
    

`TIME` int(11) NOT NULL,
  
`NAME` varchar(200) NOT NULL,
 

`MESSAGE` varchar(10000) NOT NULL,
  
`PRIVATE_COMMENTS` int(11) DEFAULT '0',

`MAIN_TIME` int(11) DEFAULT NULL,

PRIMARY KEY (`ID`)

) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;