CREATE TABLE `NOTIFICATIONS_SETTINGS` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`USER_ID` int(11) DEFAULT NULL,
  
`SUBSCRIBERS` int(11) DEFAULT '1',
  
`PHOTOS_LIKES` int(11) DEFAULT '1',
  
`PHOTOS_COMMENTS` int(11) DEFAULT '1',
  
`VIDEOS_LIKES` int(11) DEFAULT '1',
  
`VIDEOS_COMMENTS` int(11) DEFAULT '1',
  
`BLOGS_COMMENTS` int(11) DEFAULT '1',
  
`BLOGS_LIKES` int(11) DEFAULT '1',
  
`GUESTBOOK` int(11) DEFAULT '1',
  
`NEWS_LIKES` int(11) DEFAULT '1',
  
`NEWS_COMMENTS` int(11) DEFAULT '1',
  
`FORUM_LIKES` int(11) DEFAULT '1',
  
`FORUM_COMMENTS` int(11) DEFAULT '1',
  
`TYPE` varchar(200) DEFAULT NULL,
  
`SET` int(11) DEFAULT '1',
  
`COMMENTS` int(11) DEFAULT '1',
  
`LIKES` int(11) DEFAULT '1',
  
`FRIENDS` int(11) DEFAULT '1',
  
`GIFTS` int(11) DEFAULT '1',
`SHARE` int(11) DEFAULT '1',  
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;