
CREATE TABLE IF NOT EXISTS `NOTIFICATIONS` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`USER_ID` int(11) DEFAULT NULL,
`OBJECT_ID` int(11) DEFAULT NULL,
`OBJECT_ID_LIST` int(11) DEFAULT NULL,
`TYPE` varchar(120) DEFAULT NULL,
`TIME` int(11) DEFAULT NULL,
`READ` int(11) DEFAULT '1',
PRIMARY KEY (`ID`))
ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
