
CREATE TABLE IF NOT EXISTS `PANEL_LOGS` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`USER_ID` int(11) DEFAULT NULL,
`NAME` varchar(300) DEFAULT NULL,
`TIME` int(11) DEFAULT NULL,
PRIMARY KEY (`ID`)
)
ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
