CREATE TABLE IF NOT EXISTS `PANEL_ACCESS_USER` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`NAME` varchar(200) DEFAULT NULL,
`ACCESS` int(11) DEFAULT '1',
PRIMARY KEY (`ID`)
)
ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


INSERT INTO `PANEL_ACCESS_USER` (`NAME`, `ACCESS`) VALUES
('Создатель', 99), 
('Пользователь', 1), 
('Системный администратор', 98);