CREATE TABLE `PANEL_ALPHA_INSTALL` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`NAME` varchar(200) DEFAULT NULL,
  
`FACT_NAME` varchar(500) DEFAULT NULL,
  
`EXT` varchar(50) DEFAULT NULL,
  
`SIZE` int(11) DEFAULT NULL,
  
`TIME` int(11) DEFAULT NULL,
  
`ACT` int(11) DEFAULT '0',
  
`SYSTEM` int(11) DEFAULT '0',
  
`UPDATE` int(11) DEFAULT '0',
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;