
CREATE TABLE IF NOT EXISTS `PANEL_THEMES` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`NAME` varchar(100) DEFAULT NULL,
`DIR` varchar(100) DEFAULT NULL,
`LOGO` varchar(200) DEFAULT NULL,
`FAVICON` varchar(200) DEFAULT NULL,
`ACT` int(11) DEFAULT '1',
`LOGO_MAX` int(11) DEFAULT '120',
`PRIORITET_TOUCH` int(11) DEFAULT '0',
`PRIORITET_WEB` int(11) DEFAULT '0',
PRIMARY KEY (`ID`)
)
ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


INSERT INTO `PANEL_THEMES` (`NAME`, `DIR`, `LOGO`, `FAVICON`, `ACT`, `PRIORITET_TOUCH`) VALUES('Touch', 'touch', 'logo.png', 'favicon.ico', '2', '1');
INSERT INTO `PANEL_THEMES` (`NAME`, `DIR`, `LOGO`, `FAVICON`, `ACT`, `PRIORITET_WEB`) VALUES('WEB', 'web', 'logo.png', 'favicon.ico', '2', '1');