CREATE TABLE IF NOT EXISTS `PANEL_ACCESS_USER_LIST` (

`ID` int(11) NOT NULL AUTO_INCREMENT,


`ID_ACCESS` int(11) DEFAULT '0',


`ID_ACCESS_LIST` int(11) DEFAULT '0',


PRIMARY KEY (`ID`)


)
ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;