
CREATE TABLE IF NOT EXISTS `PANEL_ALPHA_INSTALL_DATA` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`ID_AI` int(11) DEFAULT NULL,
`DIR` varchar(2000) DEFAULT NULL,
PRIMARY KEY (`ID`)
)
ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
