CREATE TABLE `PHOTOS` (  
`ID` int(11) NOT NULL AUTO_INCREMENT,  
`USER_ID` int(11) DEFAULT NULL,  
`ID_DIR` int(11) DEFAULT '0',  
`NAME` varchar(300) DEFAULT NULL,  
`MESSAGE` varchar(3000) DEFAULT NULL,  
`EXT` varchar(50) DEFAULT NULL,  
`SIZE` int(11) DEFAULT NULL,  
`PRIVATE_COMMENTS` int(11) DEFAULT '0',  
`TIME` int(11) DEFAULT NULL,  
`RATING` double(10,2) DEFAULT '0.00',
`ADULT` int(11) DEFAULT '0',  
`SHOW` int(11) DEFAULT '0',
`SHIF` varchar(120) DEFAULT NULL,
`PATH` varchar(100) DEFAULT NULL,
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;