CREATE TABLE `RATING_MEDAL` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`FROM` int(11) DEFAULT '0',
  
`BEFORE` int(11) DEFAULT '0',
  
`EXT` varchar(50) DEFAULT NULL,
  
`ACT` int(11) DEFAULT '1',
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;