CREATE TABLE `SMILES_SAVE` (  
`ID` int(11) NOT NULL AUTO_INCREMENT,  
`USER_ID` int(11) DEFAULT '0',
`CLICK` int(11) DEFAULT '0',  
`TIME` int(11) DEFAULT '0',  
`SMILE_ID` int(11) DEFAULT '0',
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;
