
CREATE TABLE IF NOT EXISTS `SUBSCRIBERS` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`USER_ID` int(11) DEFAULT NULL,
`MY_ID` int(11) DEFAULT NULL,
`PHOTOS` int(11) DEFAULT '1',
PRIMARY KEY (`ID`))
ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
