CREATE TABLE IF NOT EXISTS `TRANSACTIONS` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`USER_ID` int(11) DEFAULT '0',
`INFO` varchar(800) DEFAULT NULL,
`TYPE` int(1) DEFAULT '0',
`TIME` int(11) DEFAULT '0',
`SUM` double(10,2) DEFAULT '0.00',
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;