
CREATE TABLE IF NOT EXISTS `USERS_GUESTS` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`USER_ID` int(11) NOT NULL,
  
`MY_ID` int(11) NOT NULL,
  
`READ` enum('0','1') NOT NULL DEFAULT '1',
  
`COUNT` int(11) NOT NULL DEFAULT '1',
  
`TIME` int(11) NOT NULL,
  
PRIMARY KEY (`ID`)

) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
