CREATE TABLE `USERS_VISITS` ( 
`ID` int(11) NOT NULL AUTO_INCREMENT,  
`USER_ID` int(11) DEFAULT NULL,  
`TIME` int(11) DEFAULT NULL,  
`BROWSER` varchar(500) DEFAULT NULL,  
`IP` varchar(50) DEFAULT NULL,
`LOCATION` varchar(300) DEFAULT NULL,
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;
