CREATE TABLE `USERS_SETTINGS` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
  
`USER_ID` int(11) DEFAULT NULL,
  
`SCREENSAVER` varchar(100) DEFAULT NULL,
  
`AVATAR` int(11) DEFAULT '0',
  
`AVATAR_PHONE` varchar(50) DEFAULT '#EB6156',
  
`STATUS` varchar(300) DEFAULT NULL,
  
`STR` int(11) DEFAULT '10',
  
`FRIENDS_PRIVATE` int(11) DEFAULT '1',
  
`SUBSCRIBERS_PRIVATE` int(11) DEFAULT '1',
  
`FRIENDS_PRIVATE_ADD` int(11) DEFAULT '1',
  
`NAME` varchar(200) DEFAULT NULL,
  
`SURNAME` varchar(200) DEFAULT NULL,
  
`COUNTRY` varchar(200) DEFAULT NULL,
  
`CITY` varchar(200) DEFAULT NULL,
  
`REGION` varchar(200) DEFAULT NULL,
  
`D_R` int(11) DEFAULT NULL,
  
`M_R` int(11) DEFAULT NULL,
  
`G_R` int(11) DEFAULT NULL,
  
`ABOUT_ME` varchar(300) DEFAULT NULL,
  
`MY_INTERESTS` varchar(300) DEFAULT NULL,
  
`MY_MUSIC` varchar(250) DEFAULT NULL,
  
`MY_FILMS` varchar(250) DEFAULT NULL,
  
`MY_BOOKS` varchar(250) DEFAULT NULL,
  
`MY_POLITIC` int(11) DEFAULT NULL,
  
`MY_FAITH` int(11) DEFAULT NULL,
  
`MY_PROFESSION` varchar(200) DEFAULT NULL,
  
`ALKOHOL` int(11) DEFAULT NULL,
  
`SMOKING` int(11) DEFAULT NULL,
  
`FAMILY` int(11) DEFAULT NULL,
  
`MY_BODY` int(11) DEFAULT NULL,
  
`MY_NATURE` varchar(200) DEFAULT NULL,
  
`COLOR_HAIR` varchar(200) DEFAULT NULL,
  
`COLOR_EYE` varchar(200) DEFAULT NULL,
  
`HEIGHT` int(11) DEFAULT NULL,
  
`WIDTH` int(11) DEFAULT NULL,
`PRIVATE_ACCOUNT` int(11) DEFAULT '0',
`TEXT_SIZE` int(11) DEFAULT '2',
`COMMENTS_FORMAT` int(11) DEFAULT '1',
PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;