
CREATE TABLE IF NOT EXISTS `VIDEOS_DIR` (
  
`ID` int(11) NOT NULL AUTO_INCREMENT,
`USER_ID` int(11) DEFAULT NULL,
`NAME` varchar(300) DEFAULT NULL,
`PRIVATE` int(11) DEFAULT '0',
`ID_DIR` int(11) DEFAULT '0',
`PASSWORD` varchar(300) DEFAULT NULL,
`PASSWORD_SHOW` varchar(100) DEFAULT NULL,
PRIMARY KEY (`ID`))
ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
